(define (eval-quotation exp env)
  (define (convert-to-lazy-list l)
    (if (null? l)
      '()
      (list 'cons (list 'quote (car l))
            (convert-to-lazy-list (cdr l)))))
  (let ((text (cadr exp)))
    (if (list? text)
      (if (null? text)
        '()
        (eval (convert-to-lazy-list text) env))
      text)))
