(run '(assert! (meeting accounting (Monday 9am))))
(run '(assert! (meeting administration (Monday 10am))))
(run '(assert! (meeting computer (Wednesday 3pm))))
(run '(assert! (meeting administration (Friday 1pm))))
(run '(assert! (meeting whole-company (Wednesday 4pm))))
