(define (perim-rect rect)
  (* 2 (+ (width-rect rect)
	  (height-rect rect))))

(define (area-rect rect)
  (* (width-rect rect)
     (height-rect rect)))

(define (print-rect rect)
  (display "[")
  (print-point-i (first-point rect))
  (display ", ")
  (print-point-i (second-point rect))
  (display ", ")
  (print-point-i (third-point rect))
  (display ", ")
  (print-point-i (fourth-point rect))
  (display "]")
  (newline))
