(define (install-deriv)
  (define (addend operands) (car operands))
  (define (augend operands) (cadr operands))
  (define (deriv-sum operands var)
    (make-sum (deriv (addend operands) var)
              (deriv (augend operands) var)))
  (define (multiplier operands) (car operands))
  (define (multiplicand operands) (cadr operands))
  (define (deriv-product operands var)
    (make-sum (make-product (deriv (multiplier operands) var)
                            (multiplicand operands))
              (make-product (multiplier operands)
                            (deriv (multiplicand operands) var))))
  (put 'deriv '+ deriv-sum)
  (put 'deriv '* deriv-product))
