(define (raise x)
  (apply-generic 'raise x))

(define (install-raise)
  (put 'raise '(integer)
       (lambda (x)
         (make-rational x 1)))
  (put 'raise '(rational)
       (lambda (x)
         (make-real (exact->inexact (/ (car x)
                                       (cdr x))))))
  (put 'raise '(real)
       (lambda (x)
         (make-complex-from-real-imag x 0)) ))
