(define (neg-terms L)
  (if (empty-termlist? L)
    (the-empty-termlist)
    (let ((first-term (first-term L)))
      (adjoin-term (make-term (order first-term)
                              (neg (coeff first-term)))
                   (neg-terms (rest-terms L))))))
(define (neg-poly p)
  (make-poly (variable p)
             (neg-terms (term-list p))))
