(define (ripple-carry-adder a b s c)
  (if (= (length a) 1)
    (half-adder (car a) (car b) (car s) c)
    (let ((c-in (make-wire)))
      (ripple-carry-adder (cdr a) (cdr b) (cdr s) c-in)
      (full-adder (car a) (car b) c-in (car s) c))))
