(define (serialized-exchange account1 account2)
  (let ((n1 (account1 'number))
        (n2 (account2 'number))
        (serializer1 (account1 'serializer))
        (serializer2 (account2 'serializer)))
    (if (< n1 n2)
      ((serializer2 (serializer1 exchange)) account1 account2)
      ((serializer1 (serializer2 exchange)) account1 account2))))

(define (make-account-and-serializer balance account-number)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds."))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'balance) balance)
            ((eq? m 'serializer) balance-serializer)
            ((eq? m 'number) account-number)
            (else (error "Unknown request -- MAKE-ACCOUNT" m))))
    dispatch))
