(define (*-iter a b)
  (define (double n)
    (* 2 n))
  (define (halve n)
    (/ n 2))
  (define (iter a b c)
    (cond ((= b 0) c)
	  ((even? b) (iter (double a) (halve b) c))
	  (else (iter a (- b 1) (+ c a)))))
  (iter a b 0))
