(define (substring-range-check args)
  (let ((s (car args))
        (start (cadr args))
        (end (caddr args)))
    (or (and (>= start 0)
             (>= end start)
             (>= (string-length s) end))
        "Out of range argument.")))

(define (list-ref-range-check args)
  (let ((l (car args))
        (pos (cadr args)))
    (or (and (>= pos 0)
             (> (length l) pos))
        "Out of range argument.")))
