(define (compile-and-run expression)
  (let ((instructions (assemble (statements (compile expression 'val 'return))
                                eceval)))
    (set-register-contents! eceval 'val instructions)
    (set-register-contents! eceval 'flag true)
    (start eceval)))
